"""Add ClaimEdit model

Revision ID: 82cf2013e180
Revises: 
Create Date: 2024-09-03 20:11:03.297205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cf2013e180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('edit_description', sa.Text(), nullable=True),
    sa.Column('edit_message', sa.Text(), nullable=True),
    sa.Column('edit_conditions', sa.Text(), nullable=True),
    sa.Column('edit_non_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_edits')
    # ### end Alembic commands ###
