"""Add document_type column to inputs table

Revision ID: 93b9d3934039
Revises: 82cf2013e180
Create Date: 2024-09-06 15:58:50.700123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b9d3934039'
down_revision = '82cf2013e180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###
