"""Allow null values for document_name

Revision ID: e54229a48d0b
Revises: 93b9d3934039
Create Date: 2024-09-06 16:32:02.062244

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e54229a48d0b'
down_revision = '93b9d3934039'
branch_labels = None
depends_on = None

def upgrade():
    # Update existing null values in document_type
    op.execute("UPDATE inputs SET document_type = 'Unknown' WHERE document_type IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.alter_column('document_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('document_type',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inputs', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('document_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###